# Generated by Django 6.0.3 on 2026-05-01 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_board_title_alter_column_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Tablero', 'verbose_name_plural': 'Tableros'},
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['position'], 'verbose_name': 'Columna', 'verbose_name_plural': 'Columnas'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título del Tablero'),
        ),
        migrations.AlterField(
            model_name='column',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='column',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nombre de Columna'),
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7, verbose_name='Color Hex'),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite'),
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, to='boards.label', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Baja'), ('M', 'Media'), ('H', 'Alta')], default='M', max_length=1, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título de la Tarea'),
        ),
    ]
